#!/bin/bash
# ============================================================
# KinSim — Full pipeline submission script
#
# Submits all SLURM jobs in dependency order for either the
# Dictionary or cGAN pipeline.  Run this from the login node;
# do NOT submit it as a SLURM job itself.
#
# Usage:
#   bash kinsim_pipeline.sh <mode> <pairs_file> <N> <config_out> \
#       <shards_dir> <master_pkl> \
#       <pbsim3_dir> <motifs> <M> <output_dir> \
#       [checkpoint_dir]   # cgan mode only
#
# Modes:
#   dictionary   — prepare -> train+merge -> inject -> analyze
#   cgan         — prepare -> extract+merge -> train -> generate
#
# Arguments:
#   mode              Pipeline mode: 'dictionary' or 'cgan'
#   pairs_file        Input for prepare (alternating BAM / motif-source lines)
#   N                 Number of BAM/motif pairs (array size for train/extract)
#   config_out        Output config from prepare (consumed by train/extract)
#   shards_dir        Directory for intermediate .pkl shards
#   master_pkl        Path for the merged master dictionary or training data
#   pbsim3_dir        PBSIM3 output directory (species subdirs or flat layout)
#   motifs            Motif source: KinSim string, PacBio CSV, REBASE file,
#                     or per-species mapping file (lines: "species|motif_string")
#   M                 Number of genomes to inject/generate (array size)
#   output_dir        Directory for output BAM files
#   checkpoint_dir    [cgan only] Output directory for GAN checkpoints and logs
#
# Example — Dictionary mode:
#   bash kinsim_pipeline.sh dictionary \
#       pairs.txt 53 config_strains.txt \
#       shards/ master_dict.pkl \
#       pbsim3_output/ "m6A,GATC,1;m4C,CCWGG,1" 10 injected/
#
# Example — cGAN mode:
#   bash kinsim_pipeline.sh cgan \
#       pairs.txt 53 config_strains.txt \
#       cgan_shards/ master_cgan_data.pkl \
#       pbsim3_output/ "m6A,GATC,1;m4C,CCWGG,1" 10 generated/ \
#       checkpoints/
#
# Expected directory structure:
#   project/
#     pairs.txt               <- BAM / motif-source pairs (input for prepare)
#     config_strains.txt      <- generated by prepare, consumed by train/extract
#     shards/                 <- intermediate .pkl shards
#     master_dict.pkl         <- merged dictionary (dict mode)
#     master_cgan_data.pkl    <- merged training data (cgan mode)
#     checkpoints/            <- GAN checkpoints (cgan mode)
#     pbsim3_output/          <- PBSIM3 species subdirectories (or flat .fq.gz files)
#     injected/               <- output BAMs (dict mode)
#     generated/              <- output BAMs (cgan mode)
#     logs/                   <- SLURM logs
#
# All individual SLURM scripts must be in the same directory as this script.
# ============================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ---- Usage check ----
if [ "$#" -lt 10 ]; then
    echo "Usage: bash kinsim_pipeline.sh <mode> <pairs_file> <N> <config_out> \\"
    echo "           <shards_dir> <master_pkl> \\"
    echo "           <pbsim3_dir> <motifs> <M> <output_dir> \\"
    echo "           [checkpoint_dir]   # cgan mode only"
    echo ""
    echo "Modes:  dictionary | cgan"
    echo ""
    echo "Example (dictionary):"
    echo "  bash kinsim_pipeline.sh dictionary \\"
    echo "      pairs.txt 53 config_strains.txt \\"
    echo "      shards/ master_dict.pkl \\"
    echo "      pbsim3_output/ \"m6A,GATC,1\" 10 injected/"
    echo ""
    echo "Example (cgan):"
    echo "  bash kinsim_pipeline.sh cgan \\"
    echo "      pairs.txt 53 config_strains.txt \\"
    echo "      cgan_shards/ master_cgan_data.pkl \\"
    echo "      pbsim3_output/ \"m6A,GATC,1\" 10 generated/ \\"
    echo "      checkpoints/"
    exit 1
fi

MODE="$1"
PAIRS_FILE="$2"
NUM_STRAINS="$3"
CONFIG_OUT="$4"
SHARDS_DIR="$5"
MASTER_PKL="$6"
PBSIM3_DIR="$7"
MOTIFS="$8"
NUM_GENOMES="$9"
OUTPUT_DIR="${10}"
CHECKPOINT_DIR="${11:-}"

if [ "$MODE" != "dictionary" ] && [ "$MODE" != "cgan" ]; then
    echo "ERROR: mode must be 'dictionary' or 'cgan' (got '$MODE')"
    exit 1
fi

if [ "$MODE" = "cgan" ] && [ -z "$CHECKPOINT_DIR" ]; then
    echo "ERROR: cgan mode requires an 11th argument: checkpoint_dir"
    exit 1
fi

mkdir -p logs

echo "============================================================"
echo "  KinSim pipeline — mode: $MODE"
echo "============================================================"
echo "  Pairs file:         $PAIRS_FILE"
echo "  N strains (array):  $NUM_STRAINS"
echo "  Config out:         $CONFIG_OUT"
echo "  Shards dir:         $SHARDS_DIR"
echo "  Master pkl:         $MASTER_PKL"
echo "  PBSIM3 dir:         $PBSIM3_DIR"
echo "  Motifs:             $MOTIFS"
echo "  M genomes (array):  $NUM_GENOMES"
echo "  Output dir:         $OUTPUT_DIR"
if [ "$MODE" = "cgan" ]; then
    echo "  Checkpoint dir:     $CHECKPOINT_DIR"
fi
echo ""

# ============================================================
# STEP 1 — Prepare: BAM+motif pairs -> config_strains.txt
# ============================================================
echo "[1/5] Submitting: kinsim prepare"
JOB_PREPARE=$(sbatch --parsable \
    "$SCRIPT_DIR/kinsim_prepare.slurm" \
    "$PAIRS_FILE" "$CONFIG_OUT")
echo "      Job ID: $JOB_PREPARE"

# ============================================================
# DICTIONARY MODE
# ============================================================
if [ "$MODE" = "dictionary" ]; then

    # STEP 2 — Train shards (array, depends on prepare)
    # KINSIM_NO_AUTOMERGE=1 prevents the last array task from also auto-submitting a merge,
    # since we submit the merge explicitly in step 3 to obtain its job ID for chaining.
    echo "[2/5] Submitting: kinsim dictionary train (array 1-$NUM_STRAINS)"
    JOB_TRAIN=$(sbatch --parsable \
        --array="1-${NUM_STRAINS}" \
        --dependency="afterok:${JOB_PREPARE}" \
        --export="KINSIM_NO_AUTOMERGE=1,ALL" \
        "$SCRIPT_DIR/kinsim_train.slurm" \
        "$CONFIG_OUT" "$SHARDS_DIR" "$MASTER_PKL")
    echo "      Job ID: $JOB_TRAIN"

    # STEP 3 — Merge shards (single, depends on all train tasks)
    echo "[3/5] Submitting: kinsim dictionary merge"
    JOB_MERGE=$(sbatch --parsable \
        --dependency="afterok:${JOB_TRAIN}" \
        "$SCRIPT_DIR/kinsim_train.slurm" \
        "$CONFIG_OUT" "$SHARDS_DIR" "$MASTER_PKL")
    echo "      Job ID: $JOB_MERGE"

    # STEP 4 — Inject signals (array, depends on merge)
    echo "[4/5] Submitting: kinsim dictionary inject (array 1-$NUM_GENOMES)"
    JOB_INJECT=$(sbatch --parsable \
        --array="1-${NUM_GENOMES}" \
        --dependency="afterok:${JOB_MERGE}" \
        "$SCRIPT_DIR/kinsim_inject.slurm" \
        "$PBSIM3_DIR" "$MASTER_PKL" "$MOTIFS" "$OUTPUT_DIR")
    echo "      Job ID: $JOB_INJECT"

    # STEP 5 — Analyze dictionary (single, depends on merge)
    echo "[5/5] Submitting: kinsim dictionary analyze"
    JOB_ANALYZE=$(sbatch --parsable \
        --dependency="afterok:${JOB_MERGE}" \
        "$SCRIPT_DIR/kinsim_analyze.slurm" \
        "$MASTER_PKL")
    echo "      Job ID: $JOB_ANALYZE"

    echo ""
    echo "============================================================"
    echo "  Dictionary pipeline submitted"
    echo "============================================================"
    echo "  prepare:  $JOB_PREPARE"
    echo "  train:    $JOB_TRAIN  (array 1-$NUM_STRAINS)"
    echo "  merge:    $JOB_MERGE"
    echo "  inject:   $JOB_INJECT  (array 1-$NUM_GENOMES)"
    echo "  analyze:  $JOB_ANALYZE"
    echo ""
    echo "  Monitor: squeue -u \$USER"
    echo "  Output BAMs: $OUTPUT_DIR"
    echo "  Dictionary:  $MASTER_PKL"

# ============================================================
# cGAN MODE
# ============================================================
elif [ "$MODE" = "cgan" ]; then

    # STEP 2 — Extract shards (array, depends on prepare)
    # KINSIM_NO_AUTOMERGE=1 prevents double-merge (see dictionary mode comment above)
    echo "[2/5] Submitting: kinsim cgan extract (array 1-$NUM_STRAINS)"
    JOB_EXTRACT=$(sbatch --parsable \
        --array="1-${NUM_STRAINS}" \
        --dependency="afterok:${JOB_PREPARE}" \
        --export="KINSIM_NO_AUTOMERGE=1,ALL" \
        "$SCRIPT_DIR/kinsim_cgan_extract.slurm" \
        "$CONFIG_OUT" "$SHARDS_DIR" "$MASTER_PKL")
    echo "      Job ID: $JOB_EXTRACT"

    # STEP 3 — Merge shards (single, depends on all extract tasks)
    echo "[3/5] Submitting: kinsim cgan merge"
    JOB_MERGE=$(sbatch --parsable \
        --dependency="afterok:${JOB_EXTRACT}" \
        "$SCRIPT_DIR/kinsim_cgan_extract.slurm" \
        "$CONFIG_OUT" "$SHARDS_DIR" "$MASTER_PKL")
    echo "      Job ID: $JOB_MERGE"

    # STEP 4 — Train GAN (single GPU, depends on merge)
    echo "[4/5] Submitting: kinsim cgan train"
    JOB_TRAIN=$(sbatch --parsable \
        --dependency="afterok:${JOB_MERGE}" \
        "$SCRIPT_DIR/kinsim_cgan_train.slurm" \
        "$MASTER_PKL" "$CHECKPOINT_DIR")
    echo "      Job ID: $JOB_TRAIN"

    # STEP 5 — Generate signals (array, depends on train)
    # Assumes default 100 training epochs -> checkpoint_epoch100.pt
    # If you use --epochs N, the checkpoint will be checkpoint_epochN.pt
    CKPT_FILE="${CHECKPOINT_DIR}/checkpoint_epoch100.pt"
    echo "[5/5] Submitting: kinsim cgan generate (array 1-$NUM_GENOMES)"
    JOB_GENERATE=$(sbatch --parsable \
        --array="1-${NUM_GENOMES}" \
        --dependency="afterok:${JOB_TRAIN}" \
        "$SCRIPT_DIR/kinsim_cgan_generate.slurm" \
        "$PBSIM3_DIR" "$CKPT_FILE" "$MOTIFS" "$OUTPUT_DIR")
    echo "      Job ID: $JOB_GENERATE"

    echo ""
    echo "============================================================"
    echo "  cGAN pipeline submitted"
    echo "============================================================"
    echo "  prepare:   $JOB_PREPARE"
    echo "  extract:   $JOB_EXTRACT  (array 1-$NUM_STRAINS)"
    echo "  merge:     $JOB_MERGE"
    echo "  train:     $JOB_TRAIN"
    echo "  generate:  $JOB_GENERATE  (array 1-$NUM_GENOMES)"
    echo ""
    echo "  Monitor:       squeue -u \$USER"
    echo "  Output BAMs:   $OUTPUT_DIR"
    echo "  Checkpoints:   $CHECKPOINT_DIR"
    echo "  Expected ckpt: $CKPT_FILE"
    echo "  Monitor GAN:   tensorboard --logdir $CHECKPOINT_DIR/runs"

fi
